
// Code generated by stanc v2.28.1
#include <stan/model/model_header.hpp>
namespace finnish_horseshoe_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 18> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 8, column 8 to column 20)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 9, column 8 to column 25)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 10, column 8 to column 15)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 14, column 8 to column 24)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 16, column 12 to column 74)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 15, column 23 to line 17, column 9)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 15, column 8 to line 17, column 9)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 22, column 12 to column 41)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 23, column 12 to column 41)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 24, column 12 to column 36)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 21, column 23 to line 25, column 9)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 21, column 8 to line 25, column 9)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 3, column 8 to column 23)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 4, column 8 to column 26)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 8, column 15 to column 16)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 9, column 15 to column 16)",
 " (in '/Users/Cheesecake/Documents/GitHub/BAY-STATS-Project-Anfossy-Bahtaoui-Pasupathipillai/Interactive/finnish_horseshoe.stan', line 14, column 15 to column 16)"};



class finnish_horseshoe_model final : public model_base_crtp<finnish_horseshoe_model> {

 private:
  int d;
  double tau; 
  
 
 public:
  ~finnish_horseshoe_model() { }
  
  inline std::string model_name() const final { return "finnish_horseshoe_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.28.1", "stancflags = "};
  }
  
  
  finnish_horseshoe_model(stan::io::var_context& context__,
                          unsigned int random_seed__ = 0,
                          std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "finnish_horseshoe_model_namespace::finnish_horseshoe_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 13;
      context__.validate_dims("data initialization","d","int",
           std::vector<size_t>{});
      d = std::numeric_limits<int>::min();
      
      current_statement__ = 13;
      d = context__.vals_i("d")[(1 - 1)];
      current_statement__ = 13;
      check_greater_or_equal(function__, "d", d, 0);
      current_statement__ = 14;
      context__.validate_dims("data initialization","tau","double",
           std::vector<size_t>{});
      tau = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 14;
      tau = context__.vals_r("tau")[(1 - 1)];
      current_statement__ = 14;
      check_greater_or_equal(function__, "tau", tau, 0);
      current_statement__ = 15;
      validate_non_negative_index("x", "d", d);
      current_statement__ = 16;
      validate_non_negative_index("lambda", "d", d);
      current_statement__ = 17;
      validate_non_negative_index("sigma", "d", d);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = d + d + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "finnish_horseshoe_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> x;
      x = Eigen::Matrix<local_scalar_t__, -1, 1>(d);
      stan::math::fill(x, DUMMY_VAR__);
      
      current_statement__ = 1;
      x = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(d);
      Eigen::Matrix<local_scalar_t__, -1, 1> lambda;
      lambda = Eigen::Matrix<local_scalar_t__, -1, 1>(d);
      stan::math::fill(lambda, DUMMY_VAR__);
      
      current_statement__ = 2;
      lambda = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(d);
      local_scalar_t__ c;
      c = DUMMY_VAR__;
      
      current_statement__ = 3;
      c = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__, -1, 1> sigma;
      sigma = Eigen::Matrix<local_scalar_t__, -1, 1>(d);
      stan::math::fill(sigma, DUMMY_VAR__);
      
      current_statement__ = 7;
      for (int j = 1; j <= d; ++j) {
        current_statement__ = 5;
        assign(sigma,
          ((pow(rvalue(lambda, "lambda", index_uni(j)), 2) * pow(c, 2)) /
            ((pow(tau, 2) * pow(rvalue(lambda, "lambda", index_uni(j)), 2)) +
              pow(c, 2))), "assigning variable sigma", index_uni(j));
      }
      {
        current_statement__ = 12;
        for (int j = 1; j <= d; ++j) {
          current_statement__ = 8;
          lp_accum__.add(
            normal_lpdf<propto__>(rvalue(x, "x", index_uni(j)), 0.0,
              rvalue(sigma, "sigma", index_uni(j))));
          current_statement__ = 9;
          lp_accum__.add(
            cauchy_lpdf<propto__>(rvalue(lambda, "lambda", index_uni(j)),
              0.0, 1.0));
          current_statement__ = 10;
          lp_accum__.add(inv_gamma_lpdf<propto__>(c, 1.5, 1.5));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "finnish_horseshoe_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> x;
      x = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(x, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      x = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(d);
      Eigen::Matrix<double, -1, 1> lambda;
      lambda = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(lambda, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      lambda = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(d);
      double c;
      c = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      c = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double, -1, 1> sigma;
      sigma = Eigen::Matrix<double, -1, 1>(d);
      stan::math::fill(sigma, std::numeric_limits<double>::quiet_NaN());
      
      out__.write(x);
      out__.write(lambda);
      out__.write(c);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 7;
      for (int j = 1; j <= d; ++j) {
        current_statement__ = 5;
        assign(sigma,
          ((pow(rvalue(lambda, "lambda", index_uni(j)), 2) * pow(c, 2)) /
            ((pow(tau, 2) * pow(rvalue(lambda, "lambda", index_uni(j)), 2)) +
              pow(c, 2))), "assigning variable sigma", index_uni(j));
      }
      if (emit_transformed_parameters__) {
        out__.write(sigma);
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__, -1, 1> x;
      x = Eigen::Matrix<local_scalar_t__, -1, 1>(d);
      stan::math::fill(x, DUMMY_VAR__);
      
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        assign(x, in__.read<local_scalar_t__>(),
          "assigning variable x", index_uni(sym1__));
      }
      out__.write(x);
      Eigen::Matrix<local_scalar_t__, -1, 1> lambda;
      lambda = Eigen::Matrix<local_scalar_t__, -1, 1>(d);
      stan::math::fill(lambda, DUMMY_VAR__);
      
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        assign(lambda, in__.read<local_scalar_t__>(),
          "assigning variable lambda", index_uni(sym1__));
      }
      out__.write(lambda);
      local_scalar_t__ c;
      c = DUMMY_VAR__;
      
      c = in__.read<local_scalar_t__>();
      out__.write(c);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"x", "lambda", "c", "sigma"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(d)
                                                                   },
      std::vector<size_t>{static_cast<size_t>(d)}, std::vector<size_t>{
      }, std::vector<size_t>{static_cast<size_t>(d)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "x" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "lambda" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "c");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "sigma" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "x" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "lambda" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "c");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "sigma" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"x\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(d) + "},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(d) + "},\"block\":\"parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(d) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"x\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(d) + "},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(d) + "},\"block\":\"parameters\"},{\"name\":\"c\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(d) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((d + d) + 1);
      const size_t num_transformed = d;
      const size_t num_gen_quantities = 0;
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((d + d) + 1);
      const size_t num_transformed = d;
      const size_t num_gen_quantities = 0;
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 3> names__{"x", "lambda", "c"};
      const std::array<Eigen::Index, 3> constrain_param_sizes__{d, d, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}

using stan_model = finnish_horseshoe_model_namespace::finnish_horseshoe_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return finnish_horseshoe_model_namespace::profiles__;
}

#endif


